# Site settings
title: Maria Kravtsova
logo: logo.png
description: > # this means to ignore newlines until "baseurl:"
  My thoughts that made it through the overthinking process.
baseurl: "/almanac" # the subpath of your site, e.g. /blog/
url: "http://maria-kravtsova.github.io" # the base hostname & protocol for your site
twitter_username: maria_hex
github_username:  maria-kravtsova

permalink: pretty
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-paginate
